from pathlib import Path
import json,argparse
p=argparse.ArgumentParser();p.add_argument('--out',default='l0092/market');M=Path(p.parse_args().out);load=lambda n:json.loads((M/n).read_text());rows=load('results.json')['rows'];a=load('audit.json');assert a['status']=='PASS';selection=load('selection.json');new=[r for r in rows if r['candidate']!='CCI_CONTROL'];families=['المطرقة2','الابتلاع1','نجم الصباح0.5'];modes=['منفرد','متزامنCCI','لاحقCCI'];basic=[]
for fi,base in enumerate([0,6,12]):
 for mode in range(3):
  subset=[r for r in new if r['candidate']==str(base+mode)];ns=sum(x['signals'] for x in subset);tp=sum(x['matched_events'] for x in subset);ne=sum(x['events'] for x in subset);basic.append({'pattern':families[fi],'mode':modes[mode],'signals':ns,'matched':tp,'events':ne,'precision':tp/ns if ns else 0,'recall':tp/ne if ne else 0})
r={'decision':'D-L0092-REVIEW-20261007','verdict':'Defer','quality':'NOT_CONFIRMED','selected_by_asset':selection['selected_by_asset'],'adoption':'NOT AUTHORISED','audit':a,'basic_variant_aggregates':basic,'perfect_precision_cases':[{'asset':x['asset'],'id':x['candidate'],'signals':x['signals'],'matched':x['matched_events'],'recall':x['recall']} for x in new if x['precision']==1],'inference':'not measured;historical discovery only'};(M/'review.json').write_text(json.dumps(r,indent=2)+'\n')
lines=['# L0092 — نتائج تأكيد الشموع','', '1.57صفًا/171تقييمًا؛التدقيقPASS.','2.المال:not measured.','3.الصفقاتوالتكاليف:not measured.','4.المطرقة/الابتلاع/نجم الصباح بنسختينلكلمنها وثلاثطرق لكلنسخة.','5.حالات100% الصغيرةلا دليلعلىدقةمستقبلية.','6.الاختيارالمؤهلBTC فقط؛لاETH أوSOL.','7.Defer؛NOT_CONFIRMED،لااعتماد.','8.التالي:قراءةالثبات والعينةقبلتوسيعأي نموذج.']
def table(title,heads,data):
 lines.extend(['',title,'|'+'|'.join(heads)+'|','|'+'|'.join(['---']*len(heads))+'|']);lines.extend('|'+'|'.join(map(str,z))+'|' for z in data)
table('## 1.الهوية',['الحقل','القيمة'],[['المصدرقبلالقياس',a['source_commit']],['الإطار','4hBTC/ETH/SOL؛ثلاثفترات2025 السابقة'],['السياق','هبوط6شموعسابقة؛نماذجمكيفةدونفجوات'],['التوقيت','اكتمالالشمعة/الثالثةالآن؛CCIسابق1أو2شمعةفيالوضعاللاحق']])
table('## 2.المال',['المقياس','الحالة'],[['الربحية/الخروج/التكاليف/MAE/MFE','not measured — outside this phase']])
table('## 3.جميعالحالات',['العملة','ID','تنبيهات','ملتقط/أحداث','الدقة','الاسترجاع','أهلية'],[[x['asset'],x['candidate'],x['signals'],f"{x['matched_events']}/{x['events']}",f"{x['precision']:.2%}",f"{x['recall']:.2%}",x['eligible']] for x in rows])
table('## 4.توقيتالمؤهل',['العملة','ID','وسيطالتأخير'],[[x['asset'],x['candidate'],x['median_lag']] for x in new if x['eligible']])
table('## 5.الثباتللمؤهل',['العملة','ID','الفترة','NS','TP/N','P','R'],[[x['asset'],x['candidate'],i+1,z['signals'],f"{z['matched_events']}/{z['events']}",f"{z['precision']:.2%}",f"{z['recall']:.2%}"] for x in new if x['eligible'] for i,z in enumerate(x['periods'])])
table('## 6.نسخةأساسيةثابتةلكلعائلة؛ليستاختيارالأفضل',['النموذج','الطريقة','NS','TP/N','P','R'],[[x['pattern'],x['mode'],x['signals'],f"{x['matched']}/{x['events']}",f"{x['precision']:.2%}",f"{x['recall']:.2%}"] for x in basic])
table('## 7.معاييرالحكم',['المعيار','المطلوب','النتيجة'],[['أهليةكلعملة','NS20/R30%،كلربعNS3/R15%','BTCفقط'],['الدقةهدف','70%مععينةوتغطية','لااجتيازكامل'],['دقةكلعملة','55%لكلالعملات','لااختيارلكلالعملات'],['اعتمادمستقل','تحققخارجالاختيار','not measured'],['العينةوالثباتوالتأخير','100إجماليًا/20لكلعملة،Wilson60%،تأخير<=1','البوابةالكاملةغيرمحققة']])
lines+=['','كلتفاصيلالفترات والتنبيهاتومطابقاتها محفوظةفيresults.json/alerts.json. اختلافالتعريفاتعنالمراجعموثقفيREGISTRATION.md.214+فحص؟العددالفعلية216مطابقةحسابية/بادئةو9تسمياتأحداثمرجعية؛انظرaudit.json.','الاختياراتتطويرية؛لاp-value أوتفوقمصححأوتحققأعمى. لا تغييرعتبةأوتمديدنافذةمطابقةللتأكيدالمتأخر. الCCIضابطونتائجهلااعتمادهيالأخرى.','', '```bash',f"python tools/l0092/research92.py audit --package tools/l0090 --out l0092/market --source {a['source_commit']}",'python tools/l0092/review92.py --out l0092/market','```'];lines=[z.replace('214+فحص؟العددالفعلية','العددالفعلي') for z in lines];(M/'REPORT.md').write_text('\n'.join(lines)+'\n');print(json.dumps({'basic':basic,'selected':r['selected_by_asset'],'perfect':r['perfect_precision_cases']},indent=2))
