from pathlib import Path
import json,math,hashlib,time,argparse
p=argparse.ArgumentParser();p.add_argument('--out',default='l0091/market');a=p.parse_args();M=Path(a.out);load=lambda n:json.loads((M/n).read_text());rows=load('results.json')['rows'];audit=load('audit.json');assert audit['status']=='PASS';assert len(rows)==21;selection=load('selection.json')['selected_by_asset'];new=[r for r in rows if r['candidate']!='CCI_CONTROL'];chosen=[next(x for x in new if x['asset']==asset and x['candidate']==cid) for asset,cid in selection.items() if cid is not None];ns=sum(x['signals'] for x in chosen);tp=sum(x['matched_events'] for x in chosen);ne=sum(x['events'] for x in chosen);prec=tp/ns if ns else 0;recall=tp/ne if ne else 0;z=1.959963984540054;lo=(prec+z*z/(2*ns)-z*math.sqrt(prec*(1-prec)/ns+z*z/(4*ns*ns)))/(1+z*z/ns) if ns else 0
checks={'all_assets':len(chosen)==3,'sample':ns>=100 and all(x['signals']>=20 for x in chosen),'precision070':prec>=.70,'recall030':recall>=.30,'asset_precision055':len(chosen)==3 and all(x['precision']>=.55 for x in chosen),'wilson060':lo>=.60,'median_lag1':len(chosen)==3 and all(x['median_lag'] is not None and x['median_lag']<=1 for x in chosen)}
# This is a descriptive screen. No corrected statistical test/adoption verdict is fabricated.
review={'decision':'D-L0091-REVIEW-20261007','verdict':'Defer','scope_outcome':'valid negative for standalone high-precision use of these six recovery rules','source_commit':audit['source_commit'],'selected':selection,'selection_counts':{'signals':ns,'matched_events':tp,'events':ne,'precision':prec,'recall':recall,'wilson95_low_descriptive':lo},'quality_checks':checks,'quality_status':'NOT_CONFIRMED','adoption':'NOT AUTHORISED','statistical_inference':'not measured','audit':audit,'new_rule_precision_range':[min(x['precision'] for x in new),max(x['precision'] for x in new)],'new_rule_neighbor_pairs':'with/without no-lower-low gates retain the same TP in all9 asset/window-length pairs','next':'Diagnose trend/pullback context of newly captured events versus unmatched price-recovery alerts before preregistering a causal context filter.'}
for asset in selection:
 for n in ['0','2','4']:
  x=next(r for r in rows if r['asset']==asset and r['candidate']==n);y=next(r for r in rows if r['asset']==asset and r['candidate']==str(int(n)+1));assert x['matched_events']==y['matched_events'];assert x['captured_onsets_by_period']==y['captured_onsets_by_period']
(M/'lead-review.json').write_text(json.dumps(review,indent=2)+'\n')
source=review['source_commit'];lines=['# L0091 — نتيجة استرداد قمة سعرية قصيرة','','1. التنفيذ والتدقيق:PASS؛21صفًا و63تقييمًا لفترة/عملة.','2. المال: not measured — outside this phase.','3. الصفقات والتكاليف: not measured — تنبيهات وأحداث فقط.','4. دقة الحالات الجديدة: '+f"{review['new_rule_precision_range'][0]:.2%}–{review['new_rule_precision_range'][1]:.2%}"+'؛بعيدةعن70%.','5. بعض أحداث الصعود التي فاتتCCI التقطتهاالإشارةالجديدة؛مقابلتنبيهاتغيرمطابقةكثيرة.','6. العينة والتغطية متاحتان لبعضالحالات؛لا مرشح يحققهدفالدقة.','7. القرار:D-L0091-REVIEW-20261007،Defer؛NOT_CONFIRMED،لا اعتماد.','8. التالي:تشخيص سياقالاتجاه والتراجع للأحداثالإضافية قبل تثبيتفلترسعرسببي.','','## 1. الهوية والمصدر','|الحقل|القيمة|','|---|---|',f'|التسجيل قبلقياسالسوق|{source}|','|الشبكة|n=2/3/5،مع/دونشرطعدمقاعأدنى،6تعريفات|','|الضابط|CCI14−150 لـBTC/ETH،CCI21−150 لـSOL|','|البيانات|4hBTC/ETH/SOL،ثلاثمقاطع2025 السابقة؛تطويرمكشوف|','|التعريف|إغلاقأعلىقمةnشموعسابقة؛التأكيدالاختياريlowالحالية>=أدنىlowآخرشمعتين؛نبضةfalse→true|','|المطابقة|نفسالأحداثالمجمدة،±2شمعة،أولتنبيه للحدث|','','## 2. المقاييس المالية','|الحقل|الحالة|','|---|---|','|الأموال/الربحية/الرسوم/الصفقات/الخروج/MAE/MFE|not measured — outside this phase|','','## 3. جميع الحالات — لا إسقاط للصفرية','|العملة|ID|التنبيهات|الملتقط/الأحداث|الدقة|الاسترجاع|الأهلية|','|---|---|---:|---:|---:|---:|---|']
for x in rows:lines.append(f"|{x['asset']}|{x['candidate']}|{x['signals']}|{x['matched_events']}/{x['events']}|{x['precision']:.2%}|{x['recall']:.2%}|{x['eligible']}|")
lines+=['','## 4. توقيت الحالات المختارة وصفيًا','|العملة|ID|وسيطالتأخيربالشموع|','|---|---|---:|']
for x in chosen:lines.append(f"|{x['asset']}|{x['candidate']}|{x['median_lag']}|")
lines+=['','لا تعنيالأهليةاعتمادًا؛هي بوابةعددتنبيهات وتغطية فقط. اختيارBTC رقم3 يفضّلأدنىدقة بينالمقاطع وفقالمعيارالمثبت،وليسأعلىدقةكليةبعدالنتيجة.','','## 5. الثبات — كل مقطع للاختيارات الوصفية','|العملة|المقطع|التنبيهات|الملتقط/الأحداث|الدقة|الاسترجاع|','|---|---:|---:|---:|---:|---:|']
for x in chosen:
 for i,r in enumerate(x['periods']):lines.append(f"|{x['asset']}|{i+1}|{r['signals']}|{r['matched_events']}/{r['events']}|{r['precision']:.2%}|{r['recall']:.2%}|")
lines+=['','الفترات:يناير–مارس،5أبريل–30يونيو،5يوليو–30سبتمبر2025. تفاصيل63تقييمًا فيresults.json؛لم يُنتقَمقطعأفضل لإظهارالنجاح.','','## 6. القيمة فوق CCI والاختيارات','|العملة|الاختيارالوصفي|أحداثأضافها مقابلCCI|أحداثفقدها مقابلCCI|','|---|---|---:|---:|']
for x in chosen:lines.append(f"|{x['asset']}|{x['candidate']}|{x['added_events_vs_cci']}|{x['lost_events_vs_cci']}|")
lines+=['',f'التجميع بعداختيارالتطوير:{ns}تنبيهًا،{tp}/{ne}أحداث،الدقة{prec:.2%}،الاسترجاع{recall:.2%}. ليساختبارًا مستقلًا للتخصيص ولاسياسةتداول.','شرطعدمقاعأدنى لميفقدأيحدثملتقط مقارنةبنسختهدونالشرط،في9مقارنات عملة/طول؛قلّل بعضالتنبيهات فقط،وبقيتالدقةضعيفة. لا يدلذلكعلىقوةتحسينه مستقبلًا.','','## 7. معايير الحكم المثبتة','|الشرط|المطلوب|تحقق فيتجميعالاختيارات|','|---|---|---|']
labels={'all_assets':'اختيارللعملاتالثلاث','sample':'100تنبيهإجماليًا و20لكلعملة','precision070':'دقةإجمالية70%','recall030':'استرجاع30%','asset_precision055':'دقة55%لكلعملة','wilson060':'Wilsonالسفلي60%','median_lag1':'وسيطتأخير<=1شمعةلكلعملة'}
for k,v in checks.items():lines.append(f'|{k}|{labels[k]}|{v}|')
lines+=['',f'حدWilsonالسفليالوصفي={lo:.2%}؛لايصحح البحثأواعتمادالنفسالبيانات. p-value/تصحيحتعددالمحاولات:not measured. حتىلوحققتبوابةالجودةفلااعتمادفيهذاالفحصالوصفي. لا تخفيضمعاييربعدالنتيجة.','','## التدقيق والحدود','','أعادالمسارالمرجعيكلالصفوف والتنبيهات والاختيارات،وقورنتأقنعةالتعريفات الستةبمرجعScalar،وفُحصت72مطابقةحسابية/بادئةعلىالشموعالحقيقية،وتطابقت9تسمياتأحداثمعمرجعATRومطابقةمنفصل. PASS. فحصالقياسالمحسوب قبلالقراءةاللغوية محفوظفيaudit.json؛زمنالقياس'+f"{load('measure.json')['elapsed_seconds']:.3f}"+'ثانية،والتدقيق'+f"{audit['elapsed_seconds']:.3f}"+'ثانية؛زمنالتجهيز والنشرليسمنهما.','','هذاالتشخيصيدعموجودتغطيةأحداثمختلفة،ولايثبتأنالاختراقالسعريبلاقيودإشارةدقيقة. لاقياسORمعCCI أوإعادةاختيارمؤشراتخارجالشبكة. كلالفتراتسابقالاطلاع؛لا دليلأعمى أوأداءمستقبلي.','','## التالي الواحد','','تشخيصسياقالاتجاه والتراجع للأحداثالجديدة والتنبيهاتغيرالمطابقة،لتثبيتفلترسعري سببي قبلتجربةأخرى. لا إضافةأزواج عشوائيةولاعرضنتائجإعدادغيرمسجل.','','## إعادةالحساب','', '```bash',f'python tools/l0091/research91.py measure --package tools/l0090 --out l0091/market --source {source}',f'python tools/l0091/research91.py audit --package tools/l0090 --out l0091/market --source {source}','python tools/l0091/review91.py --out l0091/market','```','','## المصطلحات','|الاسم|المعنى|','|---|---|','|الدقة|نسبةالتنبيهاتالتيطابقتأحداثالصعود|','|الاسترجاع|نسبةأحداثالصعودالمرصودةالتيالتقطتهاالإشارة|','|الأهلية|عينةوتغطيةتكفيللاختيارالوصفي؛ليستجودةأواعتمادًا|']
text='\n'.join(lines)+'\n';(M/'REPORT.md').write_text(text);Path('deliverables').mkdir(exist_ok=True);Path('deliverables/L0091-RESULTS.md').write_text(text);print(json.dumps({'verdict':'Defer','selected':selection,'selected_counts':review['selection_counts'],'quality_checks':checks},indent=2))
